name: Jason Tong
description: The personal site & blog of Jason Tong
url: http://bilalquadri.com
markdown: redcarpet
pygments: true
exclude: [Rakefile, Gemfile, Gemfile.lock, s3_website.yml]
permalink: /blog/:year/:month/:day/:title
